name: essentialEmEvidencia
version: '1.0'
main: org.example.minevidencia.essentialEmEvidencia.EssentialEmEvidencia
api-version: '1.21'

commands:
  exp:
    description: Faz troca de experiência com outro jogador
    usage: /<exp> <value>
    default: true